### PR TITLE
Merged in some minor bug fixes, enhancements, and API changes.

### PR DESCRIPTION
**Pull request by MeltyPlayer**
Apologies for there being so many changes here, this is my first pull request. 

This PR makes the following changes:

_Bug fixes:_
- fixed some code and types that were causing the 32-bit build to fail 
- carried over an NPE fix from @ckosmic’s fork 

_Enhancements:_
- stopped deleting Mario and test level model/geometry when ‘make clean’ is called, since it takes ages to redownload the files each time
- carried over type changes from @ckosmic’s fork that expand the region that Mario can explore from short-range to int-range

_API changes:_
- setting debug_print_function is decoupled from init
- can now set a handler for play_sound, which intercepts when a sound would have been played

### CODE REVIEW

**Comment by jaburns** [comment]
Awesome, thanks! I'll double check it and merge either tonight or tomorrow some time.

**Comment by jaburns** [comment]
Sorry, didn't have any free time today. Will do over the weekend

**Comment by MeltyPlayer** [comment]
No problem, there's no rush. 😊

**Comment by jaburns** [comment]
Completely lost track of this sorry, will check and merge this week

**Pull request merged**
